# coding: utf-8

"""
    Adobe Analytics APIs

    The endpoints described here are routed through Adobe.io.          In order to use these endpoints you must create an oAuth client that is          subscribed to access the Adobe Analytics Reporting API.  # noqa: E501

    OpenAPI spec version: v1 - Build: 2019-10-03_20:32:29.323
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.analytics_virtual_report_suite import AnalyticsVirtualReportSuite  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalyticsVirtualReportSuite(unittest.TestCase):
    """AnalyticsVirtualReportSuite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyticsVirtualReportSuite(self):
        """Test AnalyticsVirtualReportSuite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.analytics_virtual_report_suite.AnalyticsVirtualReportSuite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
