# coding: utf-8

"""
    Adobe Analytics APIs

    The endpoints described here are routed through Adobe.io.          In order to use these endpoints you must create an oAuth client that is          subscribed to access the Adobe Analytics Reporting API.  # noqa: E501

    OpenAPI spec version: v1 - Build: 2019-10-03_20:32:29.323
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.calculatedmetrics_api import CalculatedmetricsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCalculatedmetricsApi(unittest.TestCase):
    """CalculatedmetricsApi unit test stubs"""

    def setUp(self):
        self.api = CalculatedmetricsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calculatedmetrics_create_calculated_metric(self):
        """Test case for calculatedmetrics_create_calculated_metric

        Create a new Calculated Metric  # noqa: E501
        """
        pass

    def test_calculatedmetrics_delete_calculated_metric(self):
        """Test case for calculatedmetrics_delete_calculated_metric

        Deletion of Calculated Metrics by Id  # noqa: E501
        """
        pass

    def test_calculatedmetrics_get_calculated_metric_function(self):
        """Test case for calculatedmetrics_get_calculated_metric_function

        Retrieve a calculated metric function by id  # noqa: E501
        """
        pass

    def test_calculatedmetrics_get_calculated_metric_functions(self):
        """Test case for calculatedmetrics_get_calculated_metric_functions

        Retrieve calculated metric functions  # noqa: E501
        """
        pass

    def test_calculatedmetrics_update_calculated_metric(self):
        """Test case for calculatedmetrics_update_calculated_metric

        Update an existing calculated metric  # noqa: E501
        """
        pass

    def test_calculatedmetrics_validate_calculated_metric(self):
        """Test case for calculatedmetrics_validate_calculated_metric

        Validate a calculated metric definition  # noqa: E501
        """
        pass

    def test_find_calculated_metrics(self):
        """Test case for find_calculated_metrics

        Retrieve many calculated metrics  # noqa: E501
        """
        pass

    def test_find_one_calculated_metric(self):
        """Test case for find_one_calculated_metric

        Retrieve a single calculated metric by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
