# coding: utf-8

"""
    Adobe Analytics APIs

    The endpoints described here are routed through Adobe.io.          In order to use these endpoints you must create an oAuth client that is          subscribed to access the Adobe Analytics Reporting API.  # noqa: E501

    OpenAPI spec version: v1 - Build: 2019-10-03_20:32:29.323
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dateranges_api import DaterangesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDaterangesApi(unittest.TestCase):
    """DaterangesApi unit test stubs"""

    def setUp(self):
        self.api = DaterangesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_date_range(self):
        """Test case for create_date_range

        Creates configuration for a DateRange.  # noqa: E501
        """
        pass

    def test_delete_date_range(self):
        """Test case for delete_date_range

        Deletes a DateRange.  # noqa: E501
        """
        pass

    def test_get_date_range(self):
        """Test case for get_date_range

        Retrieves configuration for a DateRange.  # noqa: E501
        """
        pass

    def test_get_date_ranges(self):
        """Test case for get_date_ranges

        Returns a list of dateranges for the user  # noqa: E501
        """
        pass

    def test_update_date_range(self):
        """Test case for update_date_range

        Updates configuration for a DateRange.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
