# coding: utf-8

"""
    Adobe Analytics APIs

    The endpoints described here are routed through Adobe.io.          In order to use these endpoints you must create an oAuth client that is          subscribed to access the Adobe Analytics Reporting API.  # noqa: E501

    OpenAPI spec version: v1 - Build: 2019-10-03_20:32:29.323
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_metadata___shares_api import ComponentMetadataSharesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentMetadataSharesApi(unittest.TestCase):
    """ComponentMetadataSharesApi unit test stubs"""

    def setUp(self):
        self.api = ComponentMetadataSharesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_share(self):
        """Test case for delete_share

        Removes the shareId and all associations from that share  # noqa: E501
        """
        pass

    def test_find_all_shares_for_company(self):
        """Test case for find_all_shares_for_company

        Returns a list of shares for the current user's company  # noqa: E501
        """
        pass

    def test_get_share_by_id(self):
        """Test case for get_share_by_id

        Retrieves an share by its id  # noqa: E501
        """
        pass

    def test_save_share(self):
        """Test case for save_share

        Saves the given share for the current user's company  # noqa: E501
        """
        pass

    def test_search_component_shares(self):
        """Test case for search_component_shares

        search for shares for several components at once  # noqa: E501
        """
        pass

    def test_shared_to_me(self):
        """Test case for shared_to_me

        get components shared with the current user by type  # noqa: E501
        """
        pass

    def test_update_shares(self):
        """Test case for update_shares

        Share components with users. WARNING: Authoritative; deletes/overwrites all pre-existing shares for the given components  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
