# coding: utf-8

"""
    Adobe Analytics APIs

    The endpoints described here are routed through Adobe.io.          In order to use these endpoints you must create an oAuth client that is          subscribed to access the Adobe Analytics Reporting API.  # noqa: E501

    OpenAPI spec version: v1 - Build: 2019-10-03_20:32:29.323
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_metadata___tags_api import ComponentMetadataTagsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentMetadataTagsApi(unittest.TestCase):
    """ComponentMetadataTagsApi unit test stubs"""

    def setUp(self):
        self.api = ComponentMetadataTagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        Removes the tagId and all associations from that tag to any components  # noqa: E501
        """
        pass

    def test_delete_tag_items(self):
        """Test case for delete_tag_items

        Disassociates all tags from the given components  # noqa: E501
        """
        pass

    def test_find_all_for_company(self):
        """Test case for find_all_for_company

        Returns a list of tags for the current user's company  # noqa: E501
        """
        pass

    def test_get_components_by_tag_name(self):
        """Test case for get_components_by_tag_name

        Retrieves component ids associated with the given tag names  # noqa: E501
        """
        pass

    def test_get_tag_by_id(self):
        """Test case for get_tag_by_id

        Retrieves an tag by its id  # noqa: E501
        """
        pass

    def test_get_tag_list_by_component_id_and_component_type(self):
        """Test case for get_tag_list_by_component_id_and_component_type

        Retrieves a tags for a given component by componentId and componentType  # noqa: E501
        """
        pass

    def test_save_tag_component_list(self):
        """Test case for save_tag_component_list

        Tag a component with one or many tags at once. WARNING: Authoritative; deletes/overwrites all pre-existing associations  # noqa: E501
        """
        pass

    def test_save_tag_list(self):
        """Test case for save_tag_list

        Saves the given tag(s) for the current user's company  # noqa: E501
        """
        pass

    def test_search_component_tags2(self):
        """Test case for search_component_tags2

        search for tags for several components at once  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
